import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ProgressBar from "@/components/global/ProgressBar";

const splineSans = Spline_Sans({
  subsets: ["latin"],  
  display: "swap",
});

export const metadata: Metadata = {
  title: "Kaizen Karate - Do Association India",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${splineSans.className} antialiased`}
      >
        <ProgressBar />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
